namespace AutoAudit;

internal static class Emitter
{
    public const string AttributeSource =
        """
        // <auto-generated/>
        #nullable enable
        namespace AutoAudit;

        /// <summary>Marks an EF Core entity class for compile-time audit field generation.</summary>
        [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
        public sealed class AuditableAttribute : System.Attribute { }
        """;

    public const string InterfaceSource =
        """
        // <auto-generated/>
        #nullable enable
        namespace AutoAudit;

        /// <summary>Implemented by all entities decorated with <see cref="AuditableAttribute"/>.</summary>
        public interface IAuditableEntity
        {
            /// <summary>UTC timestamp when the entity was first persisted.</summary>
            System.DateTimeOffset CreatedAt { get; set; }

            /// <summary>UTC timestamp when the entity was last modified.</summary>
            System.DateTimeOffset UpdatedAt { get; set; }

            /// <summary>Identity of the user who created the entity, or <c>null</c> if unknown.</summary>
            string? CreatedBy { get; set; }

            /// <summary>Identity of the user who last modified the entity, or <c>null</c> if unknown.</summary>
            string? UpdatedBy { get; set; }
        }
        """;

    public const string InterceptorSource =
        """
        // <auto-generated/>
        #nullable enable
        using Microsoft.EntityFrameworkCore;
        using Microsoft.EntityFrameworkCore.Diagnostics;

        namespace AutoAudit;

        /// <summary>
        /// EF Core interceptor that automatically populates audit fields on
        /// <see cref="IAuditableEntity"/> instances during <c>SaveChanges</c>.
        /// </summary>
        public sealed class AuditInterceptor : SaveChangesInterceptor
        {
            private readonly System.Func<string?> _getCurrentUser;

            /// <param name="getCurrentUser">
            /// Optional delegate that returns the current user identity.
            /// When <c>null</c>, user fields are set to <c>null</c>.
            /// </param>
            public AuditInterceptor(System.Func<string?>? getCurrentUser = null)
                => _getCurrentUser = getCurrentUser ?? (() => null);

            /// <inheritdoc/>
            public override InterceptionResult<int> SavingChanges(
                DbContextEventData eventData,
                InterceptionResult<int> result)
            {
                ApplyAudit(eventData.Context!);
                return base.SavingChanges(eventData, result);
            }

            /// <inheritdoc/>
            public override System.Threading.Tasks.ValueTask<InterceptionResult<int>> SavingChangesAsync(
                DbContextEventData eventData,
                InterceptionResult<int> result,
                System.Threading.CancellationToken cancellationToken = default)
            {
                ApplyAudit(eventData.Context!);
                return base.SavingChangesAsync(eventData, result, cancellationToken);
            }

            private void ApplyAudit(DbContext context)
            {
                var now = System.DateTimeOffset.UtcNow;
                var user = _getCurrentUser();

                foreach (var entry in context.ChangeTracker.Entries<IAuditableEntity>())
                {
                    if (entry.State == EntityState.Added)
                    {
                        entry.Entity.CreatedAt = now;
                        entry.Entity.CreatedBy = user;
                    }

                    if (entry.State == EntityState.Added || entry.State == EntityState.Modified)
                    {
                        entry.Entity.UpdatedAt = now;
                        entry.Entity.UpdatedBy = user;
                    }
                }
            }
        }

        /// <summary>Extension methods for registering <see cref="AuditInterceptor"/> with EF Core.</summary>
        public static class AuditInterceptorExtensions
        {
            /// <summary>
            /// Registers an <see cref="AuditInterceptor"/> that automatically sets audit fields on save.
            /// </summary>
            /// <param name="builder">The <see cref="DbContextOptionsBuilder"/> to configure.</param>
            /// <param name="getCurrentUser">Optional delegate returning the current user identity.</param>
            public static DbContextOptionsBuilder AddAuditInterceptor(
                this DbContextOptionsBuilder builder,
                System.Func<string?>? getCurrentUser = null)
                => builder.AddInterceptors(new AuditInterceptor(getCurrentUser));
        }
        """;

    public static string Emit(TypeModel model) =>
        $$"""
        // <auto-generated/>
        #nullable enable
        namespace {{model.Namespace}};

        partial class {{model.TypeName}} : global::AutoAudit.IAuditableEntity
        {
            /// <inheritdoc/>
            public System.DateTimeOffset CreatedAt { get; set; }

            /// <inheritdoc/>
            public System.DateTimeOffset UpdatedAt { get; set; }

            /// <inheritdoc/>
            public string? CreatedBy { get; set; }

            /// <inheritdoc/>
            public string? UpdatedBy { get; set; }
        }
        """;
}
